import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export interface Decision {
  action: string;
  reasoning: string;
  params?: Record<string, any>;
}

export async function think(
  role: 'client' | 'worker',
  systemPrompt: string,
  userPrompt: string
): Promise<Decision> {
  const response = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 512,
    system: systemPrompt,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const text = response.content[0].type === 'text' ? response.content[0].text : '';

  // Parse first valid JSON object from response
  const jsonMatches = text.match(/\{[^{}]*\}/g) || [];
  for (const candidate of jsonMatches) {
    try {
      const parsed = JSON.parse(candidate);
      if (parsed.action) return parsed;
    } catch {}
  }

  // Fallback: extract action from text
  return { action: 'proceed', reasoning: text };
}

export const CLIENT_SYSTEM = `You are an autonomous AI agent that commissions work from other agents using escrow contracts.
You hold USDT and create escrows to pay for tasks. You make decisions independently.

When evaluating whether to release payment for completed work, consider:
- Did the worker submit a result hash? (required)
- Is the escrow in SUBMITTED status? (required)
- Has the deadline not yet passed? (preferred but not blocking)

Always respond with valid JSON: {"action": "release"|"dispute"|"wait", "reasoning": "..."}`;

export const WORKER_SYSTEM = `You are an autonomous AI agent that discovers and completes tasks for payment via escrow contracts.
You scan for open escrows, evaluate if tasks match your capabilities, accept them, perform work, and submit results.

Your capabilities: data analysis, research summaries, token metrics, protocol analysis.
Minimum payment: 10 USDT. You need at least 30 minutes before deadline.

When evaluating a task, consider:
- Payment amount (must be >= 10 USDT)
- Deadline (must have >= 30 min remaining)
- Task description hash (you can accept any data/research task)

When performing work, generate a realistic analysis based on the task context.

Always respond with valid JSON: {"action": "accept"|"skip"|"submit", "reasoning": "...", "params": {...}}`;

export async function evaluateTask(
  amount: number,
  deadlineTimestamp: number,
  taskDescription: string
): Promise<Decision> {
  const minutesLeft = Math.floor((deadlineTimestamp - Date.now() / 1000) / 60);
  const prompt = `Open escrow available:
- Payment: ${amount} USDT
- Time remaining: ${minutesLeft} minutes
- Task: ${taskDescription}

Should I accept this task? Respond with JSON: {"action": "accept" or "skip", "reasoning": "..."}`;

  return think('worker', WORKER_SYSTEM, prompt);
}

export async function generateWork(taskContext: string): Promise<{ result: string; reasoning: string }> {
  const response = await client.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 1024,
    system: `You are a data analyst agent. Generate a realistic analysis report based on the task. Output a JSON object with your findings. Be specific with data points, even if simulated for a testnet environment.`,
    messages: [{ role: 'user', content: `Task: ${taskContext}\n\nGenerate an analysis report as a JSON object.` }],
  });

  const text = response.content[0].type === 'text' ? response.content[0].text : '{}';
  return { result: text, reasoning: 'Analysis generated by worker agent LLM' };
}

export async function evaluateSubmission(
  escrowId: number,
  resultHash: string,
  status: number
): Promise<Decision> {
  const prompt = `Escrow #${escrowId} status update:
- Status: ${status === 2 ? 'SUBMITTED (work complete)' : 'status ' + status}
- Result hash: ${resultHash}
- Result hash is non-zero: ${resultHash !== '0x0000000000000000000000000000000000000000000000000000000000000000'}

Should I verify and release payment? Respond with JSON: {"action": "release" or "dispute" or "wait", "reasoning": "..."}`;

  return think('client', CLIENT_SYSTEM, prompt);
}
